---
title: "Multinom.analysis"
author: "Smriti"
date: "2025-07-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#Install packages
```{r}
pacman::p_load(tidyverse, dplyr, readr, codyn, lme4, lmerTest, ggrepel, tictoc, ggpubr, nlme, nnet, kableExtra, webshot, broom, ggeffects, ggpubr)

```
#data upload
```{r}
df_all <- read.csv("df_all.csv")
tree_slope_aspect_elev <- read.delim("codes/data/tree_slope_aspect_elev.csv", header = TRUE)
colnames(tree_slope_aspect_elev)
colnames(df_all)

#combine slope and Aspect information to the original file
df_slope_aspect <- tree_slope_aspect_elev %>% dplyr::select(global_x, global_y, Slope, Aspect)
df_all_with_slope_aspect <- merge(df_all, df_slope_aspect, by = c("global_x", "global_y"), all.x = TRUE)

```

#Multinomial logistic regression

```{r}
# Multinomial logistic regression
str(df_all_with_slope_aspect)
colnames(df_all_with_slope_aspect)

df_all_with_slope_aspect$MERGE_SRC <- as.factor(df_all_with_slope_aspect$MERGE_SRC)
df_all_with_slope_aspect$Land_use <- as.factor(df_all_with_slope_aspect$Land_use)
df_all_with_slope_aspect <- df_all_with_slope_aspect %>% dplyr::select(-Soil_type)
df_all_with_slope_aspect<- df_all_with_slope_aspect %>% rename(Soil_type=MERGE_SRC) %>% rename(Elevation = Elevation.m.)
df_all_with_slope_aspect <- df_all_with_slope_aspect%>%
  mutate(
    Land_use = case_when(
      Land_use == "Managed Forest" ~ "Historically forested",
      Land_use == "Old growth" ~ "Historically forested",
      Land_use== "Managed/CutRegrowth"~"Historically forested",
      Land_use == "Pasture1973" ~ "Historically pasture",
      TRUE ~ Land_use
    )) %>% mutate(Soil_type=case_when(Soil_type =="Glaciofluvial_Dissolve" ~ "Glaciolacustrine", Soil_type=="Till_Dissolve" ~ "Till", TRUE~Soil_type))

unique(df_all_with_slope_aspect$Soil_type)

model <- multinom(Clusters_complete_silhouette ~ Land_use + Soil_type + Elevation + Slope, data = df_all_with_slope_aspect)
summary(model)

## checking if aspect lowers AIC or not
model2 <- multinom(Clusters_complete_silhouette ~ Land_use + Soil_type + Elevation + Slope + Aspect, data = df_all_with_slope_aspect)
summary(model2)

AIC(model, model2)

##testing for model accuracy
predicted <- predict(model2, type = "class")
table(Predicted = predicted, Actual = df_all_with_slope_aspect$Clusters_complete_silhouette)

mean(predicted == df_all_with_slope_aspect$Clusters_complete_silhouette)  #73%


# Extract coefficients and standard errors
coefficients <- summary(model)$coefficients
coefficients 
std_errors <- summary(model)$standard.errors
std_errors
# Compute z-scores
z_scores <- coefficients / std_errors
z_scores
# Compute p-values
p_values <- 2 * (1 - pnorm(abs(z_scores)))
p_values

#extract coeff from the model and exponentiate
tidy(model, conf.int = TRUE) %>% 
  kable() %>% 
  kable_styling("basic", full_width = FALSE)

# Generate the table and save it as an HTML file
model_table <- tidy(model, conf.int = TRUE) %>% 
  kable() %>% 
  kable_styling("basic", full_width = FALSE)

# Save the table as an HTML file first
save_kable(model_table, "model_table.html")

# Convert the HTML table to an image (PNG or JPEG)
webshot("model_table.html", "model_table.png")  # Or "model_table.jpeg" for JPEG format


ggeffect(model, terms = "Land_use") %>%
    plot()

ggeffect(model) %>% plot()

#Plotting results for land use
model.land.use <- ggeffect(model, terms="Land_use")

model.fig.land.use <- ggplot(data=model.land.use, aes(x=x, y=predicted, color=response.level, group=response.level))+ geom_line(size=1) + geom_point(size=4) + geom_errorbar(aes(ymin=conf.low, ymax=conf.high, color=response.level, group=response.level), width=0.5, size=1) + scale_color_manual(name="Cluster number", 
                     labels=c("1", "2", "3"), 
                     values=c("#1F77B4","#FF7F0F","#2CA02C")) + labs(x= "Management history", y = "Probability") + theme_bw() + theme(axis.text.x = element_text(color = "black", size = 10, angle = 0, hjust = .5, vjust = .5, face = "plain"), axis.text.y = element_text(color = "black", size = 18, angle = 0, hjust = 1, vjust = 0, face = "plain"),  axis.title.x = element_text(color = "black", size = 18, angle = 0, hjust = .5, vjust = 0, face = "plain"), axis.title.y = element_text(color = "black", size = 18, angle = 90, hjust = .5, vjust = 2.5, face = "plain"))  + theme( panel.grid.major = element_blank(),   panel.grid.minor = element_blank())

#Plotting results for soil type
model.soil.type <- ggeffect(model, terms="Soil_type")


model.fig.soil.type <- ggplot(data=model.soil.type, aes(x=x, y=predicted, color=response.level, group=response.level))+ geom_line(size=1) + geom_point(size=4) + geom_errorbar(aes(ymin=conf.low, ymax=conf.high, color=response.level, group=response.level), width=0.5, size=1) +  scale_color_manual(name="Cluster number", 
                     labels=c("1", "2", "3"), 
                     values=c("#1F77B4","#FF7F0F","#2CA02C")) + labs(x= "Soil types", y = "Probability") + theme_bw() + theme(axis.text.x = element_text(color = "black", size = 10, angle = 0, hjust = .5, vjust = .5, face = "plain"), axis.text.y = element_text(color = "black", size = 18, angle = 0, hjust = 1, vjust = 0, face = "plain"),  axis.title.x = element_text(color = "black", size = 18, angle = 0, hjust = .5, vjust = 0, face = "plain"), axis.title.y = element_text(color = "black", size = 18, angle = 90, hjust = .5, vjust = 2.5, face = "plain"))  + theme( panel.grid.major = element_blank(),   panel.grid.minor = element_blank())

#Plotting results for elevation
model.elevation <- ggeffect(model, terms="Elevation")

model.fig.elevation <- ggplot(data=model.elevation, aes(x=x, y=predicted, color=response.level, group=response.level))+ geom_line(size=1) + geom_point(size=4) + geom_errorbar(aes(ymin=conf.low, ymax=conf.high, color=response.level, group=response.level), width=0.5, size=1) +  scale_color_manual(name="Cluster number", 
                     labels=c("1", "2", "3"), 
                     values=c("#1F77B4","#FF7F0F","#2CA02C")) + labs(x= "Elevation (m)", y = "Probability") + theme_bw() + theme(axis.text.x = element_text(color = "black", size = 10, angle = 0, hjust = .5, vjust = .5, face = "plain"), axis.text.y = element_text(color = "black", size = 18, angle = 0, hjust = 1, vjust = 0, face = "plain"),  axis.title.x = element_text(color = "black", size = 18, angle = 0, hjust = .5, vjust = 0, face = "plain"), axis.title.y = element_text(color = "black", size = 18, angle = 90, hjust = .5, vjust = 2.5, face = "plain"))  + theme( panel.grid.major = element_blank(),   panel.grid.minor = element_blank())


#Plotting results for slope
model.slope <- ggeffect(model, terms="Slope")

model.fig.slope <- ggplot(data=model.slope, aes(x=x, y=predicted, color=response.level, group=response.level))+ geom_line(size=1) + geom_point(size=4) + geom_errorbar(aes(ymin=conf.low, ymax=conf.high, color=response.level, group=response.level), width=0.5, size=1) +  scale_color_manual(name="Cluster number", 
                     labels=c("1", "2", "3"), 
                     values=c("#1F77B4","#FF7F0F","#2CA02C")) + labs(x= "Slope (m)", y = "Probability") + theme_bw() + theme(axis.text.x = element_text(color = "black", size = 10, angle = 0, hjust = .5, vjust = .5, face = "plain"), axis.text.y = element_text(color = "black", size = 18, angle = 0, hjust = 1, vjust = 0, face = "plain"),  axis.title.x = element_text(color = "black", size = 18, angle = 0, hjust = .5, vjust = 0, face = "plain"), axis.title.y = element_text(color = "black", size = 18, angle = 90, hjust = .5, vjust = 2.5, face = "plain"))  + theme( panel.grid.major = element_blank(),   panel.grid.minor = element_blank())


###combine the figures

model.fig.combined <- ggarrange(
  model.fig.land.use, 
  model.fig.soil.type, 
  model.fig.elevation, 
  model.fig.slope, 
  nrow = 4, 
  ncol = 1, 
  common.legend = TRUE,
  labels = c("A)", "B)", "C)", "D)"))


ggsave("multinomial.fig.combined.png", model.fig.combined, dpi = 300, height = 10, width = 6, units = "in")

```
